spring.application.name=ClinicManagementSystem
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_db
spring.datasource.username=irfan
spring.datasource.password=irfan

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

